export const types = {
  FETCH_FORECAST: "FETCH_FORECAST",
  RESET_FORECAST: "RESET_FORECAST",
  UPDATE_LOCATION: "UPDATE_LOCATION",
  CHANGE_LOCATION: "CHANGE_LOCATION",
  FETCH_LOCATION: "FETCH_LOCATION",
  FETCH_LOCATION_ERROR: "FETCH_LOCATION_ERROR"
};
